from __future__ import annotations

import json
import mimetypes
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

from release_system import core


ROOT = Path(__file__).resolve().parent
DB_PATH = ROOT / "release_system.db"


class Handler(BaseHTTPRequestHandler):
    server_version = "HPCReleaseSystem/0.1"

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        try:
            if parsed.path == "/api/me":
                user = self.current_user(required=False)
                self.send_json({"user": user})
                return
            if parsed.path == "/api/state":
                self.current_user()
                self.send_json(self.state_payload())
                return
            if parsed.path.startswith("/api/artifacts/"):
                self.require_rm()
                kind = parsed.path.rsplit("/", 1)[-1]
                conn = core.connect(DB_PATH)
                release_id = self.query().get("release_id", [""])[0]
                row = conn.execute("SELECT name, content FROM artifacts WHERE release_id = ? AND kind = ?", (release_id, kind)).fetchone()
                if not row:
                    self.send_error(404, "artifact not found")
                    return
                self.send_response(200)
                self.send_header("Content-Type", "text/plain; charset=utf-8")
                self.send_header("Content-Disposition", f"attachment; filename={row['name']}")
                self.end_headers()
                self.wfile.write(row["content"].encode("utf-8"))
                return
        except Exception as exc:
            self.send_json({"error": str(exc)}, status=401)
            return
        self.serve_static(parsed.path)

    def do_POST(self) -> None:
        parsed = urlparse(self.path)
        try:
            if parsed.path == "/api/login":
                body = self.json_body()
                token = core.authenticate(core.connect(DB_PATH), body.get("username", ""), body.get("password", ""))
                if not token:
                    raise PermissionError("Invalid username or password")
                self.send_json({"ok": True}, cookies=[f"hpc_session={token}; HttpOnly; SameSite=Strict; Path=/"])
                return
            if parsed.path == "/api/import-initial":
                self.require_rm()
                body = self.json_body()
                release_id = core.import_initial_rows(
                    core.connect(DB_PATH),
                    core.parse_csv_text(body.get("release_csv", "")),
                    core.parse_csv_text(body.get("owner_csv", "")),
                    alias_text=body.get("alias_text", ""),
                    release_name=body.get("release_name") or None,
                    maca_version=body.get("maca_version") or None,
                    deadline=body.get("deadline", ""),
                )
                self.send_json({"release_id": release_id})
                return
            if parsed.path == "/api/releases/create":
                self.require_rm()
                body = self.json_body()
                release_id = core.create_release_from_previous(core.connect(DB_PATH), body["name"], maca_version=body.get("maca_version", ""), deadline=body.get("deadline", ""))
                self.send_json({"release_id": release_id})
                return
            if parsed.path == "/api/releases/admission":
                self.require_rm()
                body = self.json_body()
                result = core.run_admission_check(core.connect(DB_PATH), body["release_id"])
                self.send_json({"blockers": result})
                return
            if parsed.path == "/api/releases/open-qa":
                self.require_rm()
                body = self.json_body()
                core.open_qa(core.connect(DB_PATH), body["release_id"])
                self.send_json({"ok": True})
                return
            if parsed.path == "/api/releases/lock":
                self.require_rm()
                body = self.json_body()
                artifacts = core.lock_release(core.connect(DB_PATH), body["release_id"])
                self.send_json({"artifacts": list(artifacts)})
                return
            if parsed.path == "/api/artifacts/generate":
                self.require_rm()
                body = self.json_body()
                if body.get("final"):
                    raise RuntimeError("Final artifacts can only be generated by release lock")
                artifacts = core.generate_artifacts(core.connect(DB_PATH), body["release_id"], final=bool(body.get("final")))
                self.send_json({"artifacts": list(artifacts)})
                return
            if parsed.path == "/api/gerrit/plan":
                self.require_rm()
                body = self.json_body()
                self.send_json(core.gerrit_push_plan(core.connect(DB_PATH), body["release_id"]))
                return
            if parsed.path == "/api/apps/new":
                body = self.json_body()
                app_id = core.add_new_app_request(
                    core.connect(DB_PATH),
                    body["release_id"],
                    official_name=body["official_name"],
                    git_url=body["git_url"],
                    git_branch=body["git_branch"],
                    owner=self.user(),
                    doc_target=body.get("doc_target", "manual"),
                )
                self.send_json({"app_id": app_id})
                return
            if parsed.path == "/api/apps/update":
                body = self.json_body()
                conn = core.connect(DB_PATH)
                app = core.get_app(conn, body["app_id"])
                self.require_owner_or_rm(app)
                release = core.get_release(conn, body["release_id"])
                if release.get("state") == "release_locked":
                    raise RuntimeError("Release is locked and immutable")
                if release.get("state") == "qa_open":
                    raise RuntimeError("QA is open; changes require change request workflow")
                if self.role() == "RM" and "app" in body:
                    app_update = body["app"]
                    for key in ["official_name", "type", "description", "git_url", "git_branch", "doc_target"]:
                        if key in app_update:
                            app[key] = app_update[key]
                    if "owners" in app_update:
                        app["owners"] = app_update["owners"]
                    core.save_app(conn, app)
                def mutate(snapshot: dict) -> None:
                    snap_update = body.get("snapshot", {})
                    for key in ["release_decision", "owner_confirmed"]:
                        if key in snap_update:
                            snapshot[key] = snap_update[key]
                    if "doc" in snap_update:
                        snapshot.setdefault("doc", {}).update(snap_update["doc"])
                    if "cicd" in snap_update:
                        snapshot.setdefault("cicd", {}).update(snap_update["cicd"])
                    if "diff_confirm_all" in snap_update and snap_update["diff_confirm_all"]:
                        for diff in snapshot.get("app_info_diffs", []):
                            diff["confirmed"] = True
                    if "test_docs" in snap_update:
                        by_id = {doc["id"]: doc for doc in snapshot.get("test_docs", [])}
                        for item in snap_update["test_docs"]:
                            if item.get("id") in by_id:
                                by_id[item["id"]].update(item)
                            elif item.get("owner_added"):
                                item.setdefault("id", core.new_id("testdoc"))
                                item.setdefault("path", f"owner_added.{len(by_id) + 1}")
                                snapshot.setdefault("test_docs", []).append(item)
                updated = core.update_snapshot(conn, body["release_id"], body["app_id"], mutate)
                conn.commit()
                self.send_json({"snapshot": updated})
                return
            if parsed.path == "/api/apps/qa-pass":
                self.require_rm()
                body = self.json_body()
                snapshot = core.mark_qa_passed(core.connect(DB_PATH), body["release_id"], body["app_id"])
                self.send_json({"snapshot": snapshot})
                return
            if parsed.path == "/api/app-info":
                body = self.json_body()
                conn = core.connect(DB_PATH)
                app = core.get_app(conn, body["app_id"])
                self.require_owner_or_rm(app)
                snapshot = core.apply_app_info(conn, body["release_id"], body["app_id"], body["app_info"], source=body.get("source", "api"))
                self.send_json({"snapshot": snapshot})
                return
        except Exception as exc:
            self.send_json({"error": str(exc)}, status=400)
            return
        self.send_error(404, "unknown endpoint")

    def query(self) -> dict[str, list[str]]:
        return parse_qs(urlparse(self.path).query)

    def json_body(self) -> dict:
        size = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(size).decode("utf-8") if size else "{}"
        return json.loads(raw or "{}")

    def state_payload(self) -> dict:
        conn = core.connect(DB_PATH)
        user = self.current_user()
        releases = core.list_releases(conn)
        release_id = self.query().get("release_id", [releases[-1]["id"] if releases else ""])[0]
        apps = core.list_apps(conn)
        if user["role"] == "Owner":
            apps = [app for app in apps if user["username"] in app.get("owners", [])]
        payload = {"apps": apps, "releases": releases, "release": None, "artifacts": [], "user": user}
        if release_id:
            release = core.get_release(conn, release_id)
            if user["role"] == "Owner":
                visible = {app["id"] for app in apps}
                release["snapshots"] = {app_id: snap for app_id, snap in release["snapshots"].items() if app_id in visible}
            payload["release"] = release
            payload["artifacts"] = [dict(row) for row in conn.execute("SELECT kind, name, final, generated_at FROM artifacts WHERE release_id = ?", (release_id,))]
        return payload

    def send_json(self, payload: dict, status: int = 200, cookies: list[str] | None = None) -> None:
        body = json.dumps(payload, ensure_ascii=False, indent=2).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        for cookie in cookies or []:
            self.send_header("Set-Cookie", cookie)
        self.end_headers()
        self.wfile.write(body)

    def serve_static(self, path: str) -> None:
        rel = "index.html" if path in {"", "/"} else path.lstrip("/")
        target = (ROOT / rel).resolve()
        try:
            target.relative_to(ROOT)
        except ValueError:
            self.send_error(403, "forbidden")
            return
        if not target.exists() or target.is_dir():
            self.send_error(404, "not found")
            return
        content = target.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", mimetypes.guess_type(target.name)[0] or "application/octet-stream")
        self.send_header("Content-Length", str(len(content)))
        self.end_headers()
        self.wfile.write(content)

    def session_token(self) -> str:
        cookie = self.headers.get("Cookie", "")
        for part in cookie.split(";"):
            if part.strip().startswith("hpc_session="):
                return part.strip().split("=", 1)[1]
        return ""

    def current_user(self, *, required: bool = True) -> dict[str, str] | None:
        user = core.session_user(core.connect(DB_PATH), self.session_token())
        if required and not user:
            raise PermissionError("Login required")
        return user

    def user(self) -> str:
        return self.current_user()["username"]

    def role(self) -> str:
        return self.current_user()["role"]

    def require_rm(self) -> None:
        if self.role() != "RM":
            raise PermissionError("RM role required")

    def require_owner_or_rm(self, app: dict) -> None:
        if self.role() == "RM":
            return
        if self.role() == "Owner" and self.user() in app.get("owners", []):
            return
        raise PermissionError("Owner permission required")


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    args = parser.parse_args()
    core.connect(DB_PATH).close()
    server = ThreadingHTTPServer((args.host, args.port), Handler)
    print(f"Serving http://{args.host}:{args.port}")
    server.serve_forever()


if __name__ == "__main__":
    main()
