"""Configuration parsing and static validation helpers."""

from __future__ import annotations

import re
import shlex
from pathlib import Path

KNOWN_KEYS = [
    "LOCAL_WORKDIR",
    "REMOTE_WORKDIR",
    "CONTAINER_NAME",
    "SERVER_USER",
    "SERVER_HOST",
    "MACA_VISIBLE_DEVICES",
    "AUTO_SELECT_DEVICE_TIMEOUT_SECONDS",
    "OP_EXEC_CMD",
    "HEURISTIC_BOUND_MODE",
    "COLLECT_TIMEOUT_SECONDS",
    "SKIP_MCPROFILER",
    "REQUIRE_MCPROFILER",
    "CYCLE_TRACE_TARGET_PEU",
    "CYCLE_TRACE_DPG_PAGE_NUM",
    "CYCLE_TRACE_TARGET_AP",
    "CYCLE_TRACE_DPC_ID",
    "CYCLE_TRACE_SAMPLE_MODE",
    "CYCLE_TRACE_KERNEL_NAME",
    "CYCLE_TRACE_KERNEL_REPEAT",
    "CYCLE_TRACE_TOOLS_JSON",
    "PROFILER_PORT",
    "MACA_SOURCE_FILE",
    "MACA_LINEINFO_BINARY",
    "MACA_LINEINFO_CYCLE_TRACE_EXEC_CMD",
    "MACA_OBJDUMP_BIN",
    "MACA_OBJDUMP_ARGS",
    "MACA_LLVM_OBJDUMP_BIN",
    "ENABLE_SOURCE_LATENCY",
    "MC_TRACER_BIN",
    "CYCLE_TRACE_BIN",
    "MC_PROFILER_BIN",
]

TOOL_KEYS = ["MC_TRACER_BIN", "CYCLE_TRACE_BIN", "MC_PROFILER_BIN"]

CONFIG_PATH = "config/trace_report_env.yaml"
ACTIVE_CONFIG_REL_PATH = ".trace-report/config/trace_report_env.yaml"

class ConfigError(Exception):
    pass

def derive_run_env(run_dir: str) -> dict[str, str]:
    basename = Path(run_dir).name.rstrip("/")
    match = re.fullmatch(r"(?P<kernel>.+)_v(?P<version>[0-9]+)_(?P<tag>.+)", basename)
    if not match:
        raise ConfigError(
            "run directory basename must match <kernel>_v<N>_<tag>: "
            f"{basename}"
        )
    return {
        "PROFILE_RUN_DIR": run_dir.rstrip("/"),
        "PROFILE_TAG": match.group("tag"),
        "PROFILE_KERNEL": match.group("kernel"),
        "PROFILE_VERSION": f"v{match.group('version')}",
    }

def strip_inline_comment(text: str) -> str:
    in_single = False
    in_double = False
    escaped = False
    out = []
    for ch in text:
        if escaped:
            out.append(ch)
            escaped = False
            continue
        if ch == "\\" and in_double:
            out.append(ch)
            escaped = True
            continue
        if ch == "'" and not in_double:
            in_single = not in_single
            out.append(ch)
            continue
        if ch == '"' and not in_single:
            in_double = not in_double
            out.append(ch)
            continue
        if ch == "#" and not in_single and not in_double:
            break
        out.append(ch)
    return "".join(out).strip()

def parse_scalar(raw: str) -> str:
    value = strip_inline_comment(raw)
    if value == "":
        return ""
    if (value.startswith('"') and value.endswith('"')) or (
        value.startswith("'") and value.endswith("'")
    ):
        inner = value[1:-1]
        if value.startswith('"'):
            out = []
            escaped = False
            for ch in inner:
                if escaped:
                    out.append(ch)
                    escaped = False
                    continue
                if ch == "\\":
                    escaped = True
                    continue
                out.append(ch)
            if escaped:
                out.append("\\")
            return "".join(out)
        return inner.replace("''", "'")
    if value.lower() in {"null", "~"}:
        return ""
    return value

def quote_scalar(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

def format_config_text(config: dict[str, str]) -> str:
    lines = ["# trace-report active environment config.", "# Generated by trace_report_env.py init-config."]
    for key in KNOWN_KEYS:
        lines.append(f"{key}: {quote_scalar(config.get(key, ''))}")
    return "\n".join(lines) + "\n"

def load_config(path: str) -> dict[str, str]:
    config_path = Path(path)
    if not config_path.is_file():
        raise ConfigError(f"config file not found: {path}")
    return parse_config_text(config_path.read_text(encoding="utf-8"), path)

def parse_config_text(text: str, source: str) -> dict[str, str]:
    config: dict[str, str] = {}
    for lineno, line in enumerate(text.splitlines(), 1):
        raw = line.strip()
        if not raw or raw.startswith("#"):
            continue
        if line[:1].isspace():
            raise ConfigError(f"{source}:{lineno}: nested YAML is not supported")
        if ":" not in raw:
            raise ConfigError(f"{source}:{lineno}: expected KEY: value")
        key, value = raw.split(":", 1)
        key = key.strip()
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
            raise ConfigError(f"{source}:{lineno}: invalid key: {key}")
        if key not in KNOWN_KEYS:
            raise ConfigError(f"{source}:{lineno}: unknown config key: {key}")
        config[key] = parse_scalar(value)
    normalize_config(config)
    return config

def normalize_config(config: dict[str, str]) -> dict[str, str]:
    for key in KNOWN_KEYS:
        config.setdefault(key, "")
    if not config["AUTO_SELECT_DEVICE_TIMEOUT_SECONDS"]:
        config["AUTO_SELECT_DEVICE_TIMEOUT_SECONDS"] = "120"
    return config

def local_active_config_path(config: dict[str, str]) -> Path:
    local_workdir = value(config, "LOCAL_WORKDIR").rstrip("/")
    if not local_workdir:
        raise ConfigError("LOCAL_WORKDIR must not be empty before writing active config")
    return Path(local_workdir) / ACTIVE_CONFIG_REL_PATH

def value(config: dict[str, str], key: str) -> str:
    return config.get(key, "")

def parse_bool(value: str) -> bool | None:
    clean = value.strip().lower()
    if clean in {"1", "true", "yes", "y", "on"}:
        return True
    if clean in {"0", "false", "no", "n", "off"}:
        return False
    return None

def bool_text(config: dict[str, str], key: str) -> str:
    parsed = parse_bool(value(config, key))
    return "true" if parsed else "false"

def target_mode(config: dict[str, str]) -> str:
    has_container = bool(value(config, "CONTAINER_NAME"))
    has_ssh = bool(value(config, "SERVER_USER") or value(config, "SERVER_HOST"))
    if has_container and has_ssh:
        return "ssh+docker"
    if has_container:
        return "docker"
    if has_ssh:
        return "ssh"
    return "local"

def parse_exec_cmd(config: dict[str, str]) -> list[str] | None:
    try:
        return shlex.split(value(config, "OP_EXEC_CMD"))
    except ValueError:
        return None
