"""Phase 0 golden fixture capture script.

Creates an isolated temp DB seeded with a small representative dataset, boots
the current server.py as a subprocess on an ephemeral port, fires a
representative set of GET + POST /api/* requests, and writes each response as a
golden file under tests/golden/responses/<name>.json.

Usage (from repo root):
    python tests/golden/capture.py

Environment:
    HPC_ADMIN_PASSWORD  — optional; defaults to "golden_admin_pw" for capture runs

The script is fully self-contained: it does NOT depend on pytest or conftest.py.
Re-running it overwrites the golden files in place.

Alignment with tests/conftest.py (impl-testbase):
    tests/conftest.py exposes seed_release / seed_cicd_task / seed_wiki_article /
    seed_snapshot / seed_cicd_request as plain module-level helpers that are
    importable here.  This script uses its own slightly richer seed (3 apps vs. 1,
    plus artifacts + release schedule) so the goldens cover more response shapes.
    Phase 2 replay uses the conftest fixtures for the authoritative minimal DB;
    this seed is only for the golden recording session.  The user roster is shared
    — both call core.ensure_default_user which core.connect invokes automatically.
"""

from __future__ import annotations

import json
import os
import shutil
import signal
import socket
import subprocess
import sys
import tempfile
import time
from pathlib import Path

# Repo root is two directories above this file (tests/golden/capture.py -> root)
REPO_ROOT = Path(__file__).resolve().parent.parent.parent

# Output directory for golden files
RESPONSES_DIR = Path(__file__).resolve().parent / "responses"

# Fixed admin password used only for capture runs so the DB stays deterministic
CAPTURE_ADMIN_PW = "golden_admin_pw"

# Artifact kinds the server exposes
ARTIFACT_KINDS = ["release_note", "manual", "ai4sci", "data"]


# ---------------------------------------------------------------------------
# Scrubber — normalises non-deterministic fields so golden diffs are stable
# ---------------------------------------------------------------------------

# Fields whose values are replaced with a stable placeholder
_SCRUB_KEYS = {
    # timestamps / date-times
    "created_at", "updated_at", "submitted_at", "reviewed_at", "delivered_at",
    "generated_at", "released_locked_at", "uploaded_at", "last_visited_at",
    "returned_at",
    # session / token fields
    "token",
    # job ids generated by secrets.token_urlsafe
    "job_id",
    # audit id (auto-increment, varies by run order)
    # "id" is intentionally NOT scrubbed globally — app_id / task_id / release_id
    # are meaningful identity keys we want to keep.
}

# Top-level response keys that may contain large or always-changing bodies
_SCRUB_ARTIFACT_CONTENT_KEYS = {"content"}

_PLACEHOLDER_TS = "SCRUBBED_TIMESTAMP"
_PLACEHOLDER_TOKEN = "SCRUBBED_TOKEN"
_PLACEHOLDER_ID = "SCRUBBED_ID"


def scrub(obj, *, _key: str = "") -> object:
    """Recursively replace non-deterministic fields with stable placeholders.

    Rules:
    - Keys in _SCRUB_KEYS → replaced by a typed placeholder string.
    - The 'ts' key (audit table timestamp) → _PLACEHOLDER_TS.
    - The 'now' / 'generated_at' in QA reports → _PLACEHOLDER_TS.
    - Nested dicts and lists are recursively scrubbed.
    """
    if isinstance(obj, dict):
        out: dict = {}
        for k, v in obj.items():
            if k in _SCRUB_KEYS:
                if "token" in k or k == "job_id":
                    out[k] = _PLACEHOLDER_TOKEN
                else:
                    out[k] = _PLACEHOLDER_TS
            elif k == "ts":
                out[k] = _PLACEHOLDER_TS
            elif k == "password_hash":
                out[k] = "SCRUBBED_HASH"
            else:
                out[k] = scrub(v, _key=k)
        return out
    if isinstance(obj, list):
        return [scrub(item, _key=_key) for item in obj]
    return obj


# ---------------------------------------------------------------------------
# DB seeding
# ---------------------------------------------------------------------------

SEED_CSV_TEXT = """\
官方名称,类型,APP类型,Owner,app_version,maca_chip,hpcc_chip,arch,maca_version,git_url,git_branch
GoldenAmber,HPC,分子动力学,owner_test,22,"c500,x301",x201,x86,20260511,ssh://gerrit/PDE/HPC/hpc_amber,maca
GoldenLammps,AI4Sci,分子动力学,owner_test,stable,,,,20260511,ssh://gerrit/PDE/HPC/hpc_lammps,main
GoldenHpl,HPC,高性能计算,owner_test,2.3,c500,,x86,20260511,ssh://gerrit/PDE/HPC/hpc_hpl,maca
"""


def seed_db(db_path: Path, admin_password: str) -> dict:
    """Seed the SQLite DB at db_path with a minimal representative dataset.

    Returns a dict of key IDs (release_id, app_ids, cicd_task_id, wiki_article_id)
    so capture() can form correct request URLs/bodies.
    """
    # Import here so the script works when run from repo root
    sys.path.insert(0, str(REPO_ROOT))
    from release_system import core
    from release_system.wiki import core as wiki_core

    conn = core.connect(db_path)

    # 1. Create admin user (mirrors server.py ensure_admin_user logic)
    core.create_user(conn, "admin", admin_password, "Admin")

    # 2. Seed default users (rm / owner_test / qa / spd_test / guest)
    #    ensure_default_user is already called by core.connect → init_db, but
    #    calling it again is idempotent.
    core.ensure_default_user(conn)

    # 3. Import initial CSV → creates first release and three apps
    rows = list(core.parse_csv_text(SEED_CSV_TEXT))
    release_id = core.import_initial_rows(
        conn,
        rows,
        release_name="Golden-Release-1",
        maca_version="20260511",
        app_freeze_deadline="2026-12-31 23:59",
        doc_deadline="2026-12-31 23:59",
    )

    # 4. Collect app_ids from the seeded release
    release = core.get_release(conn, release_id)
    app_ids = list(release["snapshots"].keys())

    # 5. Seed a CICD task via RM auto-approve path (RM submitter → immediately approved)
    cicd_payload = {
        "app_name": "GoldenAmber",
        "app_version": "22",
        "repo_type": "git",
        "repo_name": "ssh://gerrit/PDE/HPC/hpc_amber",
        "branch": "maca",
        "build_product": ["maca"],
        "community_artifact": [],
        "build_image": "hpc/amber-builder:latest",
        "test_timeout": 40,
        "owner_username": "owner_test",
        "status": "Running",
        "notes": "golden capture seed task",
    }
    cicd_req = core.submit_cicd_request(
        conn,
        task_id=None,
        request_type="create",
        payload=cicd_payload,
        submitter="rm",
        submitter_role="RM",
        submitter_display="RM User",
    )
    cicd_task_id = cicd_req["task_id"]

    # 6. Also leave a pending Owner CICD request so /api/cicd/requests shows variety
    core.submit_cicd_request(
        conn,
        task_id=cicd_task_id,
        request_type="modify",
        payload={"notes": {"old": "golden capture seed task", "new": "owner wants change"}},
        submitter="owner_test",
        submitter_role="Owner",
        submitter_display="Owner Test",
    )

    # 7. Seed a wiki article (RM role — required by wiki WRITE_ROLES)
    wiki_article = wiki_core.save_article(
        conn,
        article_id=None,
        title="Golden Test Article",
        body_md="# Golden\nThis is a golden capture test article.",
        pinned=False,
        user="rm",
        role="RM",
    )
    wiki_article_id = wiki_article["id"]

    # 8. Set QA status on one app so /api/qa-reports has something
    qa_items = [{"app_id": app_ids[0], "status": "qa_passed", "note": "golden qa note"}]
    core.qa_set_status_batch(conn, release_id, qa_items, user="qa", role="QA")

    # 9. Generate artifacts (release_note, manual, ai4sci, data) for the release
    try:
        core.generate_artifacts(conn, release_id, final=False)
    except Exception as exc:
        print(f"  [warn] generate_artifacts: {exc}")

    # 10. Seed a release schedule entry
    core.upsert_release_schedule(
        conn,
        entry_id=None,
        version="Golden-2.0",
        branch_cut_at="2026-07-01",
        release_at="2026-08-01",
        note="golden schedule entry",
        user="rm",
        role="RM",
    )

    conn.commit()
    conn.close()

    return {
        "release_id": release_id,
        "app_ids": app_ids,
        "first_app_id": app_ids[0] if app_ids else "",
        "cicd_task_id": cicd_task_id,
        "wiki_article_id": wiki_article_id,
    }


# ---------------------------------------------------------------------------
# Free port helper
# ---------------------------------------------------------------------------

def find_free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


# ---------------------------------------------------------------------------
# Server lifecycle
# ---------------------------------------------------------------------------

def wait_for_server(host: str, port: int, timeout: float = 15.0) -> None:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with socket.create_connection((host, port), timeout=0.3):
                return
        except OSError:
            time.sleep(0.1)
    raise RuntimeError(f"Server at {host}:{port} did not become ready within {timeout}s")


# ---------------------------------------------------------------------------
# HTTP client (using httpx)
# ---------------------------------------------------------------------------

def _make_headers(cookie: str) -> dict[str, str]:
    headers: dict[str, str] = {"Content-Type": "application/json"}
    if cookie:
        headers["Cookie"] = cookie
    return headers


def _client() -> "httpx.Client":
    """Return an httpx client with proxy bypassed for localhost.

    The environment may have http_proxy set (e.g. 127.0.0.1:3576 MCP proxy).
    We always talk directly to the test server on 127.0.0.1 so we must disable
    environment proxy pickup.
    """
    import httpx
    return httpx.Client(trust_env=False, timeout=15)


def _do_get(base: str, path: str, cookie: str, params: str = "") -> tuple[int, object, dict]:
    url = f"{base}{path}"
    if params:
        url = f"{url}?{params}"
    with _client() as client:
        resp = client.get(url, headers=_make_headers(cookie), follow_redirects=False)
    try:
        body = resp.json()
    except Exception:
        body = resp.text
    return resp.status_code, body, dict(resp.headers)


def _do_post(base: str, path: str, cookie: str, payload: dict) -> tuple[int, object, dict, str]:
    """Returns (status, body, headers, new_cookie)."""
    with _client() as client:
        resp = client.post(
            f"{base}{path}",
            content=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
            headers=_make_headers(cookie),
            follow_redirects=False,
        )
    new_cookie = cookie
    set_cookie = resp.headers.get("set-cookie", "")
    if "hpc_session=" in set_cookie:
        for part in set_cookie.split(";"):
            if part.strip().startswith("hpc_session="):
                new_cookie = part.strip()
                break
    try:
        body = resp.json()
    except Exception:
        body = resp.text
    return resp.status_code, body, dict(resp.headers), new_cookie


# ---------------------------------------------------------------------------
# Golden file writer
# ---------------------------------------------------------------------------

def write_golden(name: str, status: int, body: object, note: str = "",
                  expected_status: int | None = None) -> None:
    RESPONSES_DIR.mkdir(parents=True, exist_ok=True)
    scrubbed = scrub(body)
    record = {
        "_golden_name": name,
        "_note": note,
        "status": status,
        "body": scrubbed,
    }
    out_path = RESPONSES_DIR / f"{name}.json"
    out_path.write_text(json.dumps(record, ensure_ascii=False, indent=2), encoding="utf-8")
    # Use caller-supplied expected_status to decide the label; otherwise treat <400 as OK
    exp = expected_status if expected_status is not None else (200 if status < 400 else None)
    ok_mark = "OK" if status == (exp if exp is not None else status) and status < 500 else "ERR"
    print(f"  [{ok_mark}] {name}  HTTP {status}  -> {out_path.name}")


# ---------------------------------------------------------------------------
# Main capture routine
# ---------------------------------------------------------------------------

def capture(db_path: Path, port: int, ids: dict) -> None:
    base = f"http://127.0.0.1:{port}"
    release_id = ids["release_id"]
    first_app_id = ids["first_app_id"]
    cicd_task_id = ids["cicd_task_id"]
    wiki_article_id = ids["wiki_article_id"]

    cookie = ""

    print("\n--- Phase 1: Login ---")

    # POST /api/login (admin)
    status, body, headers, cookie = _do_post(base, "/api/login", cookie, {
        "username": "admin",
        "password": CAPTURE_ADMIN_PW,
    })
    write_golden("post_login_admin", status, body, "Admin login response body")
    admin_cookie = cookie

    # POST /api/login (rm) — capture RM session for role-restricted endpoints
    status, body, headers, rm_cookie = _do_post(base, "/api/login", "", {
        "username": "rm",
        "password": "rm",
    })
    write_golden("post_login_rm", status, body, "RM login response body")

    # POST /api/login (owner)
    status, body, headers, owner_cookie = _do_post(base, "/api/login", "", {
        "username": "owner_test",
        "password": "owner_test",
    })
    write_golden("post_login_owner", status, body, "Owner login response body")

    # POST /api/login (qa)
    status, body, headers, qa_cookie = _do_post(base, "/api/login", "", {
        "username": "qa",
        "password": "qa",
    })
    write_golden("post_login_qa", status, body, "QA login response body")

    print("\n--- Phase 2: Public / lightweight GET endpoints ---")

    # GET /api/me (unauthenticated)
    status, body, _ = _do_get(base, "/api/me", "")
    write_golden("get_me_unauthenticated", status, body, "me with no session -> user: null")

    # GET /api/me (RM session)
    status, body, _ = _do_get(base, "/api/me", rm_cookie)
    write_golden("get_me_rm", status, body, "me with RM session")

    # GET /api/ldap/status
    status, body, _ = _do_get(base, "/api/ldap/status", "")
    write_golden("get_ldap_status", status, body, "LDAP status (public endpoint)")

    print("\n--- Phase 3: Core state ---")

    # GET /api/state (RM, with release_id)
    status, body, _ = _do_get(base, "/api/state", rm_cookie, f"release_id={release_id}")
    write_golden("get_state_rm", status, body, "/api/state for RM with seeded release")

    # GET /api/state (Owner)
    status, body, _ = _do_get(base, "/api/state", owner_cookie, f"release_id={release_id}")
    write_golden("get_state_owner", status, body, "/api/state for Owner")

    print("\n--- Phase 4: CICD workbench ---")

    # GET /api/cicd/tasks
    status, body, _ = _do_get(base, "/api/cicd/tasks", rm_cookie)
    write_golden("get_cicd_tasks", status, body, "list all CICD tasks")

    # GET /api/cicd/tasks (status filter)
    status, body, _ = _do_get(base, "/api/cicd/tasks", rm_cookie, "status=Running")
    write_golden("get_cicd_tasks_running", status, body, "CICD tasks filtered to Running")

    # GET /api/cicd/tasks/{id}/history
    status, body, _ = _do_get(base, f"/api/cicd/tasks/{cicd_task_id}/history", rm_cookie)
    write_golden("get_cicd_task_history", status, body, "task request history")

    # GET /api/cicd/requests (RM view, all)
    status, body, _ = _do_get(base, "/api/cicd/requests", rm_cookie)
    write_golden("get_cicd_requests_rm", status, body, "CICD requests RM view")

    # GET /api/cicd/requests (RM view, pending only)
    status, body, _ = _do_get(base, "/api/cicd/requests", rm_cookie, "status=pending")
    write_golden("get_cicd_requests_pending", status, body, "CICD requests pending only")

    # GET /api/cicd/requests (owner, only_mine)
    status, body, _ = _do_get(base, "/api/cicd/requests", owner_cookie, "only_mine=1")
    write_golden("get_cicd_requests_owner_mine", status, body, "Owner's own CICD requests")

    # GET /api/cicd/notifications (RM)
    status, body, _ = _do_get(base, "/api/cicd/notifications", rm_cookie)
    write_golden("get_cicd_notifications_rm", status, body, "CICD notification counts for RM")

    # GET /api/cicd/notifications (Owner)
    status, body, _ = _do_get(base, "/api/cicd/notifications", owner_cookie)
    write_golden("get_cicd_notifications_owner", status, body, "CICD notification counts for Owner")

    # GET /api/cicd/deliveries (RM)
    status, body, _ = _do_get(base, "/api/cicd/deliveries", rm_cookie)
    write_golden("get_cicd_deliveries_rm", status, body, "CICD deliveries RM view")

    print("\n--- Phase 5: QA reports ---")

    # GET /api/qa-reports
    status, body, _ = _do_get(base, "/api/qa-reports", rm_cookie, f"release_id={release_id}")
    write_golden("get_qa_reports", status, body, "QA reports for seeded release")

    print("\n--- Phase 6: Wiki ---")

    # GET /api/wiki/articles (RM — Owner/RM/Admin can read)
    status, body, _ = _do_get(base, "/api/wiki/articles", rm_cookie)
    write_golden("get_wiki_articles", status, body, "list wiki articles (RM)")

    # GET /api/wiki/articles/{id}
    status, body, _ = _do_get(base, f"/api/wiki/articles/{wiki_article_id}", rm_cookie)
    write_golden("get_wiki_article_by_id", status, body, "single wiki article")

    # GET /api/wiki/articles/{id} — 404 for nonexistent (intentional)
    status, body, _ = _do_get(base, "/api/wiki/articles/wiki_doesnotexist", rm_cookie)
    write_golden("get_wiki_article_404", status, body, "nonexistent wiki article returns 404",
                 expected_status=404)

    print("\n--- Phase 7: Artifacts ---")

    for kind in ARTIFACT_KINDS:
        status, body, _ = _do_get(base, f"/api/artifacts/{kind}", rm_cookie,
                                  f"release_id={release_id}")
        # Artifact responses are plain text/CSV, not JSON — wrap them
        record_body: object
        if isinstance(body, str):
            # Truncate large bodies; record first 500 chars for readability
            record_body = body[:500] + ("...[truncated]" if len(body) > 500 else "")
        else:
            record_body = body
        write_golden(f"get_artifact_{kind}", status, record_body,
                     f"artifact kind={kind} for seeded release")

    print("\n--- Phase 8: Test scope CSV ---")

    # GET /api/test-scope.csv (RM)
    status, body, _ = _do_get(base, "/api/test-scope.csv", rm_cookie,
                               f"release_id={release_id}")
    csv_preview: object
    if isinstance(body, str):
        csv_preview = body[:500] + ("...[truncated]" if len(body) > 500 else "")
    else:
        csv_preview = body
    write_golden("get_test_scope_csv", status, csv_preview, "test-scope CSV for RM")

    print("\n--- Phase 9: App audit ---")

    # GET /api/app-audit (RM)
    status, body, _ = _do_get(base, "/api/app-audit", rm_cookie,
                               f"app_id={first_app_id}&release_id={release_id}")
    write_golden("get_app_audit", status, body, "audit log for first seeded app")

    print("\n--- Phase 10: Admin endpoints ---")

    # GET /api/admin/users (Admin)
    status, body, _ = _do_get(base, "/api/admin/users", admin_cookie)
    write_golden("get_admin_users", status, body, "user list (Admin only)")

    print("\n--- Phase 11: Representative POSTs ---")

    # POST /api/qa/status-batch (QA) — use qa_passed (has_issues requires non-empty note)
    qa_payload = {
        "release_id": release_id,
        "items": [
            {"app_id": first_app_id, "status": "qa_passed", "note": "golden qa passed"},
        ],
    }
    status, body, _, _ = _do_post(base, "/api/qa/status-batch", qa_cookie, qa_payload)
    write_golden("post_qa_status_batch", status, body, "QA status batch update (qa_passed)")

    # POST /api/apps/update — RM updates snapshot (release_decision)
    update_payload = {
        "app_id": first_app_id,
        "release_id": release_id,
        "snapshot": {"release_decision": "cicd_only"},
    }
    status, body, _, _ = _do_post(base, "/api/apps/update", rm_cookie, update_payload)
    write_golden("post_apps_update_decision", status, body,
                 "RM updates release_decision on first app")

    # POST /api/apps/update — RM updates doc fields
    doc_update_payload = {
        "app_id": first_app_id,
        "release_id": release_id,
        "snapshot": {
            "doc": {"intro": "Golden intro text for parity test."},
        },
    }
    status, body, _, _ = _do_post(base, "/api/apps/update", rm_cookie, doc_update_payload)
    write_golden("post_apps_update_doc", status, body, "RM updates doc field on first app")

    # POST /api/cicd/notifications/mark-visited (RM)
    status, body, _, _ = _do_post(base, "/api/cicd/notifications/mark-visited", rm_cookie, {})
    write_golden("post_cicd_mark_visited", status, body, "mark CICD notifications as visited")

    # POST /api/cicd/requests/submit — Owner submits a new create request (pending)
    owner_cicd_payload = {
        "task_id": None,
        "request_type": "create",
        "payload": {
            "app_name": "GoldenLammps",
            "app_version": "stable",
            "repo_type": "git",
            "repo_name": "ssh://gerrit/PDE/HPC/hpc_lammps",
            "branch": "main",
            "build_product": ["maca"],
            "community_artifact": [],
            "build_image": "hpc/lammps:latest",
            "test_timeout": 60,
            "owner_username": "owner_test",
            "status": "Running",
            "notes": "owner golden submission",
        },
    }
    status, body, _, _ = _do_post(base, "/api/cicd/requests/submit", owner_cookie,
                                   owner_cicd_payload)
    write_golden("post_cicd_request_submit_owner", status, body,
                 "Owner submits CICD create request (enters pending queue)")

    print("\n--- Phase 12: Logout ---")

    # POST /api/logout
    status, body, _, _ = _do_post(base, "/api/logout", rm_cookie, {})
    write_golden("post_logout", status, body, "logout clears session cookie")

    print(f"\nGolden responses written to: {RESPONSES_DIR}")
    total = len(list(RESPONSES_DIR.glob("*.json")))
    print(f"Total golden files: {total}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> int:
    admin_pw = os.environ.get("HPC_ADMIN_PASSWORD", CAPTURE_ADMIN_PW)

    tmp_dir = tempfile.mkdtemp(prefix="hpc_golden_")
    db_path = Path(tmp_dir) / "golden.db"
    port = find_free_port()

    print(f"Golden capture starting")
    print(f"  Temp dir : {tmp_dir}")
    print(f"  DB path  : {db_path}")
    print(f"  Port     : {port}")

    try:
        # 1. Seed the DB before starting the server (avoids races)
        print("\nSeeding database...")
        ids = seed_db(db_path, admin_pw)
        print(f"  release_id      : {ids['release_id']}")
        print(f"  app_ids         : {ids['app_ids']}")
        print(f"  cicd_task_id    : {ids['cicd_task_id']}")
        print(f"  wiki_article_id : {ids['wiki_article_id']}")

        # 2. Launch server.py as a subprocess pointing at the seeded DB
        server_script = REPO_ROOT / "server.py"
        env = {**os.environ, "HPC_ADMIN_PASSWORD": admin_pw}
        # Override the DB path: server.py resolves DB_PATH relative to its
        # directory, so we set PYTHONPATH and pass db_path via a small wrapper
        # by using a patched invocation approach.  The simplest approach: copy
        # server.py's working directory to tmp so DB_PATH resolves correctly.
        # But server.py hardcodes DB_PATH = ROOT / "release_system.db".
        # We instead create a symlink from ROOT/release_system.db perspective
        # inside tmp_dir and launch with cwd=tmp_dir pointing at a clone, OR
        # we copy server.py and monkeypatch... The cleanest approach without
        # modifying server.py: create a tiny wrapper that patches the global.

        wrapper_path = Path(tmp_dir) / "_capture_server.py"
        wrapper_path.write_text(
            f"""\
import sys
sys.path.insert(0, {str(REPO_ROOT)!r})
import server
from pathlib import Path
server.DB_PATH = Path({str(db_path)!r})
server.ADMIN_PASSWORD_FILE = Path({str(tmp_dir)!r}) / "admin_password.local"
# Also patch core's view if it caches DB_PATH
server.main()
""",
            encoding="utf-8",
        )

        proc = subprocess.Popen(
            [sys.executable, str(wrapper_path), "--host", "127.0.0.1", "--port", str(port)],
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            cwd=str(REPO_ROOT),
        )

        try:
            print(f"\nWaiting for server on port {port}...")
            wait_for_server("127.0.0.1", port, timeout=20.0)
            print("Server ready.")

            # 3. Fire representative requests and record goldens
            capture(db_path, port, ids)

        finally:
            print("\nShutting down server...")
            proc.terminate()
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                proc.kill()
                proc.wait()
            # Print server stderr for diagnostics if any lines present
            stderr_out = proc.stderr.read().decode("utf-8", errors="replace") if proc.stderr else ""
            if stderr_out.strip():
                print("[server stderr]")
                for line in stderr_out.splitlines()[-30:]:
                    print(" ", line)

    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)

    return 0


if __name__ == "__main__":
    sys.exit(main())
